---
# tasks file for nginxLive
- name: Install nginx
  ansible.builtin.yum:
    name: nginx
    state: present
    update_cache: yes
- name: Copy file with owner and permissions
  ansible.builtin.copy:
    src: files/index.html
    dest: /home/ritik/
    owner: root
    group: root
    mode: "0644"
